### ISSUE TITLE
Font URL rewrites in autoptimizeStyles

### ISSUE THREAD

**Issue by denydias** [futtta/autoptimize#18]
Just moving [this thread](https://wordpress.org/support/topic/font-rewrites-in-css) into here to document it in a more appropriate context.

**Comment by denydias** [comment]
Hi @futtta,

I've made some progress with this one, although a pull request is not possible yet. I had some troubles integrating the code into AO that I want to share with you.

Let me start by providing a stylesheet snippet, a pretty usual one with lots of variations. Please save it as `styles.css`.

```css
#customer .section-title{ font-family: ralewaymedium, "Helvetica Neue", Helvetica, Arial, sans-serif; }
.parallax-overlay-pattern.style_one { background-image: url(" http://wedev.local:8080/wp-content/themes/brooklyn/images/overlay-pattern.png") !important; }
.parallax-overlay-pattern.style_two { background-image: url(" http://wedev.local:8080/wp-content/themes/brooklyn/images/overlay-pattern2.png") !important; }

@font-face {
	font-family: 'FontAwesome';
	src:
		url(//exemple.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.eot);
	src:
		url(//exemple.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.eot) format('embedded-opentype'),
		url(//exemple.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.woff2) format('woff2'),
		url(//exemple.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.woff) format('woff'),
		url(//exemple.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.ttf) format('truetype'),
		url(//exemple.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.svg#fontawesomeregular) format('svg');
	font-weight: normal;
	font-style: normal
}

@font-face {
	font-family: 'ralewayregular';
	src:
		url(//example.com/wp-content/themes/brooklyn/css/fonts/raleway-regular-webfont.eot);
	src:
		url(//example.com/wp-content/themes/brooklyn/css/fonts/raleway-regular-webfont.eot?#iefix) format('embedded-opentype'),
		url(//example.com/wp-content/themes/brooklyn/css/fonts/raleway-regular-webfont.woff) format('woff'),
		url(//example.com/wp-content/themes/brooklyn/css/fonts/raleway-regular-webfont.ttf) format('truetype'),
		url(//example.com/wp-content/themes/brooklyn/css/fonts/raleway-regular-webfont.svg#ralewayregular) format('svg');
	font-weight: normal;
	font-style: normal
}
@font-face {
	font-family: 'flexslider-icon';
	src:
		url(//exemple.com:8080/wp-content/themes/brooklyn/css/fonts/flexslider-icon.eot);
	src:
		url(//exemple.com:8080/wp-content/themes/brooklyn/css/fonts/flexslider-icon.eot?#iefix) format('embedded-opentype'),
		url(//exemple.com:8080/wp-content/themes/brooklyn/css/fonts/flexslider-icon.woff) format('woff'),
		url(//exemple.com/wp-content/themes/brooklyn/css/fonts/flexslider-icon.ttf) format('truetype'),
		url(//exemple.com/wp-content/themes/brooklyn/css/fonts/flexslider-icon.svg#flexslider-icon) format('svg');
	font-weight: normal;
	font-style: normal
}
@font-face {
	font-family: 'ssbp';
	src:
		url('//exemple.com/wp-content/plugins/simple-share-buttons-plus/sharebuttons/assets/fonts/ssbp.eot?xj3ol1');
	src:
		url('//exemple.com/wp-content/plugins/simple-share-buttons-plus/sharebuttons/assets/fonts/ssbp.eot?#iefixxj3ol1') format('embedded-opentype'),
		url('//exemple.com/wp-content/plugins/simple-share-buttons-plus/sharebuttons/assets/fonts/ssbp.woff?xj3ol1') format('woff'),
		url('//exemple.com/wp-content/plugins/simple-share-buttons-plus/sharebuttons/assets/fonts/ssbp.ttf?xj3ol1') format('truetype'),
		url('//exemple.com/wp-content/plugins/simple-share-buttons-plus/sharebuttons/assets/fonts/ssbp.svg?xj3ol1#ssbp') format('svg');
	font-weight: normal;
	font-style: normal;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale
}
```

Now let's see the standalone code to replace `@font-face` urls. Save it as regex.php in the same directory where `style.css` is.

```php
<?php

define('AUTOPTIMIZE_WP_SITE_URL',"https://wedev.local:8080/");
$cdn_url = "https://cdn-provider.com/";
$code = file_get_contents("styles.css");

// Do the fonts!
// set regex'es
$fontface_regex = '/@font-face\s*(\{(?:[^{}]+|(?1))*\})/';
$scheme_regex = "/(https?:)?/";
$domain_regex = "/\/\/([[:alnum:]\-\.]+)(:[0-9]+)?\//i";
// first get all @font-face content in $code
preg_match_all($fontface_regex, $code, $matches);
if ((is_array($matches)) && (!empty($cdn_url))) {
	// then, for each @font-face found, replace urls
	foreach($matches[0] as $fontface){
		$site_url_noscheme = preg_replace($scheme_regex, "", AUTOPTIMIZE_WP_SITE_URL);
		$cdn_url_noscheme = preg_replace($scheme_regex, "", $cdn_url);
		$cdn_fontface = str_replace($site_url_noscheme, $cdn_url_noscheme, $fontface);
		$code = str_replace($fontface, $cdn_fontface, $code);
	}
	echo $code;
}
```

Runtime and output:

```php
$ time php regex.php
#customer .section-title{ font-family: ralewaymedium, "Helvetica Neue", Helvetica, Arial, sans-serif; }
.parallax-overlay-pattern.style_one { background-image: url(" http://wedev.local:8080/wp-content/themes/brooklyn/images/overlay-pattern.png") !important; }
.parallax-overlay-pattern.style_two { background-image: url(" http://wedev.local:8080/wp-content/themes/brooklyn/images/overlay-pattern2.png") !important; }

@font-face {
	font-family: 'FontAwesome';
	src:
		url(//cdn-provider.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.eot);
	src:
		url(//cdn-provider.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.eot) format('embedded-opentype'),
		url(//cdn-provider.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.woff2) format('woff2'),
		url(//cdn-provider.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.woff) format('woff'),
		url(//cdn-provider.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.ttf) format('truetype'),
		url(//cdn-provider.com/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.svg#fontawesomeregular) format('svg');
	font-weight: normal;
	font-style: normal
}

@font-face {
	font-family: 'ralewayregular';
	src:
		url(//cdn-provider.com/wp-content/themes/brooklyn/css/fonts/raleway-regular-webfont.eot);
	src:
		url(//cdn-provider.com/wp-content/themes/brooklyn/css/fonts/raleway-regular-webfont.eot?#iefix) format('embedded-opentype'),
		url(//cdn-provider.com/wp-content/themes/brooklyn/css/fonts/raleway-regular-webfont.woff) format('woff'),
		url(//cdn-provider.com/wp-content/themes/brooklyn/css/fonts/raleway-regular-webfont.ttf) format('truetype'),
		url(//cdn-provider.com/wp-content/themes/brooklyn/css/fonts/raleway-regular-webfont.svg#ralewayregular) format('svg');
	font-weight: normal;
	font-style: normal
}

@font-face {
	font-family: 'flexslider-icon';
	src:
		url(//cdn-provider.com/wp-content/themes/brooklyn/css/fonts/flexslider-icon.eot);
	src:
		url(//cdn-provider.com/wp-content/themes/brooklyn/css/fonts/flexslider-icon.eot?#iefix) format('embedded-opentype'),
		url(//cdn-provider.com/wp-content/themes/brooklyn/css/fonts/flexslider-icon.woff) format('woff'),
		url(//cdn-provider.com/wp-content/themes/brooklyn/css/fonts/flexslider-icon.ttf) format('truetype'),
		url(//cdn-provider.com/wp-content/themes/brooklyn/css/fonts/flexslider-icon.svg#flexslider-icon) format('svg');
	font-weight: normal;
	font-style: normal
}

@font-face {
	font-family: 'ssbp';
	src:
		url('//cdn-provider.com/wp-content/plugins/simple-share-buttons-plus/sharebuttons/assets/fonts/ssbp.eot?xj3ol1');
	src:
		url('//cdn-provider.com/wp-content/plugins/simple-share-buttons-plus/sharebuttons/assets/fonts/ssbp.eot?#iefixxj3ol1') format('embedded-opentype'),
		url('//cdn-provider.com/wp-content/plugins/simple-share-buttons-plus/sharebuttons/assets/fonts/ssbp.woff?xj3ol1') format('woff'),
		url('//cdn-provider.com/wp-content/plugins/simple-share-buttons-plus/sharebuttons/assets/fonts/ssbp.ttf?xj3ol1') format('truetype'),
		url('//cdn-provider.com/wp-content/plugins/simple-share-buttons-plus/sharebuttons/assets/fonts/ssbp.svg?xj3ol1#ssbp') format('svg');
	font-weight: normal;
	font-style: normal;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale
}
real    0m0.068s
user    0m0.054s
sys     0m0.012s
```

Works pretty nice for every URL and leave alone others not inside `@font-face` blocks. And it's also pretty fast.

When I put this code into `classes/autoptimizeStyles.php`, the troubles begin. I have tried to integrate this in two ways:

1. **Before** ``// Do the imaging!``:

  * In this case, it does nothing. Absolutely nothing. There are no URL substituitions at all, which is very strange because at this point `$code` is already populated.

2. **After**

  ```php
  if(!empty($imgreplace)) {
    $code = str_replace(array_keys($imgreplace),array_values($imgreplace),$code);
  }
  ```

  I get this:

	```css
	@font-face {
		font-family: 'FontAwesome';
		src:
			url(//minsky.local:8080/wp-content/themes/brooklyn/images/overlay-pattern2.png/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.eot);
		src:
			url(//minsky.local:8080/wp-content/themes/brooklyn/images/overlay-pattern2.png/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.eot) format('embedded-opentype'),
			url(//minsky.local:8080/wp-content/themes/brooklyn/images/overlay-pattern2.png/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.woff2) format('woff2'),
			url(//minsky.local:8080/wp-content/themes/brooklyn/images/overlay-pattern2.png/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.woff) format('woff'),
			url(//minsky.local:8080/wp-content/themes/brooklyn/images/overlay-pattern2.png/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.ttf) format('truetype'),
			url(//minsky.local:8080/wp-content/themes/brooklyn/images/overlay-pattern2.png/wp-content/plugins/ut-shortcodes/css/fonts/fontawesome-webfont.svg#fontawesomeregular) format('svg');
		font-weight: normal;
		font-style: normal;
	}
	```

  Note the url replacement. It now have a `/wp-content/themes/brooklyn/images/overlay-pattern2.png` that's not inside any other `@font-face` block. I don't have a clue on how it came up there!

In both cases, I have placed many debug stuff in AO code so it gave me a glimpse of what's on going on there, but no luck.

Can you please take a look on that when you get some spare time so I can move on with this new feature?

Thank you very much.
