### ISSUE TITLE
CSS Invalid

### ISSUE THREAD

**Issue by m-O-rpheus** [futtta/autoptimize#419]
Unfortunately, with the current version 3.1.12, the CSS becomes invalid due to Autoptimize, especially when combined with CSS nesting.

```css
.container {
	& .parent {
		scroll-padding: 0px max((((100% - var(--wrapper-big)) / 2) + var(--wrapper-padding)), var(--wrapper-padding));

		& .item + .item {
			margin-left: var(--wrapper-padding);
		}
	}
}
```
<img width="735" alt="Screen2" src="https://github.com/user-attachments/assets/d6a1af4c-3654-4d5b-9a9e-5821168bb60c">

In the example, which contains the Adjacent sibling combinator ".item + .item", the spaces around the + inside the calc (max) are removed. This makes the CSS invalid and it does not work.
